/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MacConfig */

#ifndef _Included_MacConfig
#define _Included_MacConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MacConfig
 * Method:    isShiftDownNative
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_MacConfig_isShiftDownNative
  (JNIEnv *, jclass);

/*
 * Class:     MacConfig
 * Method:    resolveAlias
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MacConfig_resolveAlias
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
