/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowsConfig */

#ifndef _Included_WindowsConfig
#define _Included_WindowsConfig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowsConfig
 * Method:    windowsTrash
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_WindowsConfig_trashNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     WindowsConfig
 * Method:    macAddress
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_WindowsConfig_macAddressNative
  (JNIEnv *, jclass);

/*
 * Class:     MacConfig
 * Method:    isShiftDown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_WindowsConfig_isShiftDownNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
